services:
  - type: web
    name: CalmBot-Cloud-API
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        sync: false
